Revert "tweak: use format_args for efficiency"
This reverts commit 61486fae7db044ef859fb0242844c4e5fb33ac15.

We convert the color inside the function, so we can't reference it outside the function

error[E0515]: cannot return value referencing local variable `c_u8`
   --> /home/ahann/Documents/GitHub/libcosmic/cosmic-theme/src/output/qt_output.rs:340:5
    |
340 |     format_args!("{},{},{}", c_u8.red, c_u8.green, c_u8.blue)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^----^^^^^^
    |     |                                              |
    |     |                                              `c_u8` is borrowed here
    |     returns a value referencing data owned by the current function
    |